local GSE = GSE
local Statics = GSE.Static

Statics.Patrons = {
    [[1990Causer]],
    [[6a6f686e6e79]],
    [[AJ Guckian]],
    [[ARTEX]],
    [[Aabukim]],
    [[Abdullah Al Noaimi]],
    [[Aerrek]],
    [[Aiden Gramson]],
    [[Alastorm]],
    [[Alexis Benton]],
    [[Alfred Green]],
    [[Allen Ponce]],
    [[Allero]],
    [[Amadruid]],
    [[Anaconda Gaming]],
    [[Andrew Baldwin]],
    [[Andrew Fox]],
    [[Andrew VanArman]],
    [[Anthony Welch]],
    [[Anthony0396]],
    [[Arne Krüger]],
    [[B43lzebub]],
    [[BFMVmetalA7X .]],
    [[Bearded_Gamer ]],
    [[Ben Stage]],
    [[Big_Al]],
    [[Bill coonelly]],
    [[Bizzle]],
    [[Bob]],
    [[Bob Pieters]],
    [[Bowdacious ]],
    [[Brad ]],
    [[Brandon Henry]],
    [[Brenda]],
    [[Brian Dickerson]],
    [[Brian Rud Sørensen]],
    [[Bruce Wardle]],
    [[Bryan Erickson]],
    [[CapSisko ]],
    [[Carlos Rivera]],
    [[Charles]],
    [[Chele]],
    [[Chris Esparza]],
    [[Chris Juengel]],
    [[Chris Livingston]],
    [[Chris Parker]],
    [[Christopher Lee]],
    [[Clayton Johnson]],
    [[Comicus]],
    [[Corey Ebert]],
    [[Craig McDormand]],
    [[Curtis Parenzin]],
    [[DJ]],
    [[Daniel Best]],
    [[Daniel Capper]],
    [[Daniel Friberg]],
    [[DarkLichNY ]],
    [[David A Bell]],
    [[David Arton-Powell]],
    [[David Blanchard]],
    [[Davis Campos]],
    [[Diesel]],
    [[DlSepu]],
    [[DocTock]],
    [[Donald Easter]],
    [[Donna W.]],
    [[Doug Sims]],
    [[Dougiedougiedougie]],
    [[Ed Choe]],
    [[Edmond]],
    [[Edward Yanke]],
    [[ElementNine]],
    [[Elfyau]],
    [[Eric Stoeckel Jr]],
    [[Erik P.]],
    [[Euben Hadd]],
    [[Fen]],
    [[Frankie Lee]],
    [[Froh987]],
    [[FullSpect]],
    [[Gaimon Chris]],
    [[Gary]],
    [[Gary Mills]],
    [[Gddmitspiros]],
    [[George McCubbins]],
    [[Gerald McCandless]],
    [[Gilbert Mejia]],
    [[Gimz]],
    [[Glenn van Kooijk]],
    [[Gregory ]],
    [[Gutitout]],
    [[Gyrt]],
    [[GấuPanda]],
    [[Hansth ]],
    [[Holger]],
    [[J.R. Hughes]],
    [[JIMA JONES]],
    [[Jack Etienne]],
    [[Jakob Andersen]],
    [[Jamie Currier]],
    [[Jared Landolt]],
    [[Jason ]],
    [[Jason DeLawder]],
    [[Jasper Hengefeld]],
    [[Jay  Gomez]],
    [[Jed Hollander]],
    [[Jeff Powell]],
    [[Jeffrey Daniels]],
    [[Jennifer Carlson]],
    [[Jens Schulze]],
    [[Jeremy ]],
    [[Jeremy Neumann]],
    [[Jeremy Williams]],
    [[Jessica]],
    [[Jf Boubou]],
    [[Jim]],
    [[Jimmy Tuvebrant]],
    [[Joakim Wikström]],
    [[Jodi Meese]],
    [[Joe Jackson]],
    [[Joe Lowery]],
    [[John]],
    [[John Balk]],
    [[John Baxter]],
    [[John Mitchell]],
    [[John Rose]],
    [[John Shelton]],
    [[Joker]],
    [[Joseph Atkins]],
    [[Joseph Connor]],
    [[Joseph King]],
    [[JumpyWizzard]],
    [[Junior Rodriguez]],
    [[Justin]],
    [[Justin Shaffner]],
    [[K Bee]],
    [[Kakka]],
    [[Kent Blair]],
    [[Kevin Ibrahim]],
    [[Kevin Jansen]],
    [[Kevin Polson]],
    [[Kevin T Gallaher]],
    [[Kozzen]],
    [[Kyle Stamps]],
    [[Larry Nau]],
    [[Lasse Dalh]],
    [[Laura A Clegg]],
    [[Laurie Timothy]],
    [[Leeloo]],
    [[Leo Camps]],
    [[Leonardo Bastos]],
    [[Lorna Appleby]],
    [[LrdNikon ]],
    [[Luckrider]],
    [[Luis Flores]],
    [[Luke Newland]],
    [[Lyneanne Corbett (Lyn)]],
    [[MankiGames ]],
    [[Mariusz Sawlewicz]],
    [[Mark Crane]],
    [[Mark David McCoy 34]],
    [[Martin Vines]],
    [[Mathias Bohman]],
    [[Mathusala]],
    [[Matt Sneary]],
    [[Matthias Mosberger]],
    [[Megan Sims (Blenderkitten)]],
    [[Melchy]],
    [[Melissa N Anderson]],
    [[Michael Castronovo]],
    [[Michael Irving]],
    [[Michael R Kauffmann]],
    [[Michael Swancott]],
    [[Michael Wilson]],
    [[Miguel Alvarez]],
    [[Mikel Carrascosa Alonso]],
    [[Mikkel Juul Jørgensen]],
    [[MolarMacros]],
    [[Mosh]],
    [[MrCynic]],
    [[Mustafa Kamil]],
    [[Mystik]],
    [[Narz]],
    [[Nate]],
    [[NightWeasel ]],
    [[Noah Burge]],
    [[Nora Kirschling]],
    [[Nuclone101]],
    [[OAK]],
    [[OLDT1MER ]],
    [[Oof Ooferington]],
    [[P]],
    [[Passy No]],
    [[Patrick Lüke]],
    [[Patrick O'Hagan]],
    [[Paul Kingman]],
    [[Paul Westervelt]],
    [[Paweł Kuczyński]],
    [[Per Jensen]],
    [[Peter Masters]],
    [[Philip Bird]],
    [[Philip Schulze]],
    [[Pyred]],
    [[Randy G]],
    [[Ravn Maniac]],
    [[Ray Craft]],
    [[Ray Feliciano]],
    [[Reginald Zwartjes]],
    [[Rhyvon]],
    [[Ricardo Carrizo]],
    [[Rickey C]],
    [[Rob Richardson]],
    [[Robert Czymoch]],
    [[Robert Noble]],
    [[Robert Rogers]],
    [[Robert Sims]],
    [[Robert Wears]],
    [[Rogério Martins Regalo]],
    [[Russell Baker]],
    [[Ryan Phipps]],
    [[Ryo]],
    [[Samma]],
    [[Samuel L Spencer]],
    [[Santiago Draco]],
    [[Saoud Ali]],
    [[ScaryLarryGames]],
    [[Schiwouna Schi]],
    [[Scott Flippo]],
    [[Sebastian Sorger]],
    [[Senor Mule]],
    [[Sh4wdy]],
    [[Shelves]],
    [[Shtev]],
    [[Simon Wilcock]],
    [[Slatorius]],
    [[Slowdog]],
    [[Sol Space Engineers]],
    [[Steve Clink]],
    [[Steven Allison]],
    [[Steven Shaw]],
    [[Steven Short]],
    [[Steven T Brewer]],
    [[Sumith Imtiaz]],
    [[TheArabianLord]],
    [[Thomas Young]],
    [[Thore Kvalheim]],
    [[Thunderlipz ]],
    [[TitleTown Wrestling]],
    [[Tom Straugh]],
    [[Topcat357]],
    [[Toril Harink ]],
    [[Travis Gosselink]],
    [[Tyler Griffiths]],
    [[Typical Panda]],
    [[Uistean]],
    [[Umenneske94]],
    [[Valcyn]],
    [[Victor Hodges]],
    [[Vince Orlando]],
    [[Vincent Murcia]],
    [[Ward Perdue]],
    [[Warren Jumper]],
    [[Wazwaz]],
    [[William ]],
    [[William J Hiatt]],
    [[Wraith]],
    [[Xingudi]],
    [[Yourhighness]],
    [[Zemmer]],
    [[alvin parker]],
    [[amshagar ]],
    [[babalou]],
    [[bearno2021]],
    [[bunchishi tawara]],
    [[ccvc]],
    [[coot ]],
    [[crogin]],
    [[crystaltech]],
    [[devlik]],
    [[giorgino]],
    [[iAmRad]],
    [[jack tapper]],
    [[jay garcia]],
    [[jianqiang sun]],
    [[joel cadett]],
    [[johnehokanson]],
    [[jordon mabry]],
    [[jp]],
    [[kelly jarrell]],
    [[kristian montevecchi]],
    [[martin frimand]],
    [[migro]],
    [[mike saul]],
    [[neofodder]],
    [[nyloel ]],
    [[pantinhatv]],
    [[phillip corlett]],
    [[pudkud]],
    [[ralf heckel]],
    [[ralph chubbuck]],
    [[roberto sebilla]],
    [[thibaux]],
    [[troy tallent]],
    [[tyreek73 Mcn]],
    [[wynne clark]],
    [[xXGhozh2Xx]],
    [[zibiken]]
}